"use client";

import Link from "next/link";
import { signInWithPopup } from "firebase/auth";
import { useState } from "react";
import { auth, googleProvider, isFirebaseConfigured } from "@/lib/firebase";
import { Icon } from "@/components/icon";

export default function AuthCard() {
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  async function continueWithGoogle() { setError(""); if (!auth || !isFirebaseConfigured) { setError("Google sign-in is almost ready. Add the Firebase values from .env.example to .env.local first."); return; } setLoading(true); try { await signInWithPopup(auth, googleProvider); window.location.assign("/"); } catch { setError("Google sign-in could not open. Please try again."); } finally { setLoading(false); } }
  return <main className="relative grid min-h-screen place-items-center overflow-hidden px-5 py-10"><div aria-hidden="true" className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_15%_15%,rgba(248,173,127,.37),transparent_28%),radial-gradient(circle_at_85%_18%,rgba(188,151,244,.32),transparent_31%),radial-gradient(circle_at_50%_95%,rgba(103,205,179,.2),transparent_31%),linear-gradient(135deg,#faf6ef,#f4f0f7_58%,#eef7f2)]" /><div aria-hidden="true" className="orb-one absolute -left-28 top-8 -z-10 size-80 rounded-full bg-[#ed9e86]/20 blur-[90px]" /><div aria-hidden="true" className="orb-two absolute -right-24 bottom-6 -z-10 size-88 rounded-full bg-[#8f7ae8]/20 blur-[100px]" /><section className="reveal w-full max-w-[440px] rounded-[30px] border border-white/90 bg-white/72 p-7 shadow-[0_30px_85px_rgba(76,61,93,.18)] backdrop-blur-2xl sm:p-9"><Link href="/" className="inline-flex items-center gap-2 text-sm font-semibold text-[#504862] transition hover:text-[#785cbd]"><span className="grid size-7 place-items-center rounded-full bg-[linear-gradient(135deg,#886ee9,#df83aa)] text-white"><Icon name="sparkle" className="size-3.5" /></span> ProblemFirst</Link><div className="mt-12"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#8067bf]">A little more continuity</p><h1 className="mt-4 text-4xl font-semibold leading-[.98] tracking-[-.065em] text-[#302a39]">Keep your next<br />steps close.</h1><p className="mt-5 text-sm leading-6 text-[#756e7d]">Sign in to carry the useful parts of today into whatever comes next.</p></div><button onClick={continueWithGoogle} disabled={loading} className="pressable mt-9 flex h-13 w-full items-center justify-center gap-3 rounded-[17px] border border-[#e5dfe9] bg-white px-5 text-sm font-semibold text-[#3f384b] shadow-[0_10px_20px_rgba(66,52,80,.09)] transition hover:-translate-y-0.5 hover:border-[#c9b9e9] hover:shadow-[0_14px_28px_rgba(94,70,140,.16)] disabled:cursor-not-allowed disabled:opacity-70"><Icon name="google" className="size-[18px] text-[#5a67d8]" />{loading ? "Opening Google…" : "Continue with Google"}</button>{error && <p role="alert" className="mt-4 rounded-xl bg-[#fff0f1] px-3 py-2 text-xs leading-5 text-[#a24c61]">{error}</p>}<p className="mt-8 text-center text-xs leading-5 text-[#938b9a]">By continuing, you agree to use ProblemFirst responsibly. We keep your sign-in private and simple.</p></section></main>;
}
