import "@fontsource/dm-serif-display/latin-400.css";
import "@fontsource/manrope/latin-400.css";
import "@fontsource/manrope/latin-500.css";
import "@fontsource/manrope/latin-600.css";
import "@fontsource/manrope/latin-700.css";
import type { Metadata } from "next";
import Background from "@/components/background";
import { Icon } from "@/components/icon";
import SiteHeader from "@/components/site-header";

export const metadata: Metadata = { title: "For businesses" };

const framework = [
  ["01", "Define the moment", "Connect an offering to the specific real-life moment it can improve—not a broad audience label."],
  ["02", "Make the fit clear", "Explain the outcome, the limits, and the person it is genuinely useful for."],
  ["03", "Arrive with context", "Appear beside a useful next step, when attention is high and the recommendation is earned."],
];

export default function BusinessPage() {
  return <main className="business-sans min-h-screen overflow-hidden border border-white/10 bg-[#14130f]/60 text-white shadow-[0_0_90px_rgba(211,170,91,.08)] backdrop-blur-xl">
    <Background mode="business" />
    <SiteHeader />
    <section className="mx-auto max-w-[1280px] px-5 pb-28 pt-16 sm:px-8 sm:pt-22 lg:px-10">
      <div className="grid gap-12 border-b border-white/10 pb-16 lg:grid-cols-[.94fr_1.06fr] lg:items-end">
        <div className="reveal"><p className="inline-flex items-center gap-2 rounded-md border border-[#dfc485]/25 bg-[#d5af5e]/10 px-3 py-1.5 text-[10px] font-bold tracking-[.16em] text-[#e3c98c]"><Icon name="building" className="size-3.5" /> PARTNER WITH PROBLEMFIRST</p><h1 className="business-serif mt-8 max-w-xl text-5xl leading-[.91] tracking-[-.045em] text-[#fcf8ef] sm:text-7xl">Relevance is<br />a <span className="text-[#d7b56d]">better</span> kind<br />of visibility.</h1><p className="mt-7 max-w-[470px] text-[15px] leading-7 text-white/55">Build a presence around the moments your work makes lighter. ProblemFirst puts thoughtful businesses in front of people looking for a real next step.</p><div className="mt-9 flex flex-wrap items-center gap-4"><a href="mailto:hello@problemfirst.app?subject=ProblemFirst%20business%20interest" className="pressable inline-flex items-center gap-2 rounded-lg bg-[#f4e6c6] px-5 py-3 text-sm font-bold text-[#292116] shadow-[0_12px_30px_rgba(202,163,88,.16)] hover:bg-white">Start a conversation <Icon name="arrow" className="size-4" /></a><span className="text-xs leading-5 text-white/38">For teams that value<br />usefulness over volume.</span></div></div>
        <PartnerDashboard />
      </div>
      <section className="grid gap-10 border-b border-white/10 py-18 lg:grid-cols-[.75fr_1.25fr] lg:py-24"><div className="reveal"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#d9ba78]">A different discovery layer</p><h2 className="business-serif mt-5 max-w-sm text-4xl leading-[.97] tracking-[-.035em] text-[#fcf8ef]">The product is never the whole story.</h2><p className="mt-5 max-w-xs text-sm leading-6 text-white/48">People do not need another list of options. They need the right direction, with the right support available when it matters.</p></div><div className="grid gap-px overflow-hidden rounded-xl border border-white/10 bg-white/10 sm:grid-cols-3">{framework.map(([number, title, description], index) => <article className={`card-lift reveal ${index === 1 ? "bg-[#211c14]" : "bg-[#171510]"} p-6 sm:p-7`} style={{ animationDelay: `${(index + 1) * 120}ms` }} key={number}><p className="text-[10px] font-bold tracking-[.18em] text-[#d5b36d]">{number}</p><h3 className="mt-14 text-lg font-semibold tracking-[-.045em] text-[#faf6ed]">{title}</h3><p className="mt-3 text-sm leading-6 text-white/45">{description}</p></article>)}</div></section>
      <section className="grid gap-8 py-18 lg:grid-cols-[1.04fr_.96fr] lg:py-24"><div className="reveal overflow-hidden rounded-xl border border-white/10 bg-[#15130f]/60 shadow-[0_18px_50px_rgba(0,0,0,.18)] backdrop-blur-xl"><div className="flex items-center justify-between border-b border-white/8 px-5 py-4 sm:px-6"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#d6b778]">How a placement earns trust</p><p className="mt-1 text-xs text-white/38">Product → moment → meaningful direction</p></div><span className="rounded-md border border-[#d8b873]/20 bg-[#d8b873]/10 px-2 py-1 text-[9px] font-bold tracking-[.1em] text-[#e9cf94]">EXAMPLE</span></div><div className="grid gap-px bg-white/8 sm:grid-cols-[.95fr_1.05fr]"><div className="bg-[#17150f] p-6"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-white/35">A person is asking</p><p className="business-serif mt-5 text-2xl leading-[1.05] text-[#f6f0e5]">“How can I make my desk setup stop hurting my back?”</p><div className="mt-8 border-l border-[#d4ae61] pl-3 text-xs leading-5 text-white/45">The context is physical comfort during focused desk work—not simply “office furniture.”</div></div><div className="bg-[#1d1811] p-6"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#dfc486]">Suggested direction</p><div className="mt-5 border border-white/10 bg-white/[.045] p-4"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg bg-[#f0e2c4] text-[#755d34]">◌</span><div><p className="text-sm font-semibold text-[#fbf6ec]">Ergonomic workspace support</p><p className="mt-1 text-[11px] text-white/43">Desk accessories · posture support</p></div></div><p className="mt-4 text-xs leading-5 text-white/52">Shown because it supports the exact next step, with a clear expectation of what it can help improve.</p></div></div></div></div><aside className="reveal delay-2 flex flex-col justify-between border-l border-white/10 py-2 pl-0 lg:pl-10"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#d9ba78]">Designed for considered teams</p><h2 className="business-serif mt-5 max-w-md text-4xl leading-[.97] tracking-[-.035em] text-[#fcf8ef]">A better signal than another click.</h2><p className="mt-5 max-w-sm text-sm leading-6 text-white/48">The opportunity is not to interrupt a person. It is to be there when the fit is clear and the intent is already present.</p></div><div className="mt-10 grid grid-cols-2 border-y border-white/10 py-5"><Stat value="Contextual" label="Every placement begins with a real-life problem." /><Stat value="Clear" label="People see why the support is relevant." /></div></aside></section>
      <section className="reveal grid items-center gap-6 border-t border-white/10 pt-14 sm:grid-cols-[1fr_auto]"><div><p className="business-serif text-3xl tracking-[-.035em] text-[#f8f1e6]">Useful is a more durable form of visible.</p><p className="mt-2 text-sm text-white/42">Let’s find the right place for your work in the ProblemFirst experience.</p></div><a href="mailto:hello@problemfirst.app?subject=ProblemFirst%20business%20interest" className="pressable inline-flex items-center justify-center gap-2 rounded-lg border border-[#dfc486]/35 bg-[#d9b872]/10 px-5 py-3 text-sm font-bold text-[#f5dfab] transition hover:bg-[#d9b872]/18">Talk to our team <Icon name="arrow" className="size-4" /></a></section>
    </section>
  </main>;
}

function PartnerDashboard() { return <div className="reveal delay-2 relative mx-auto w-full max-w-[560px]"><div className="absolute -inset-10 rounded-full bg-[#d1ab62]/12 blur-3xl" /><div className="relative overflow-hidden rounded-xl border border-white/12 bg-[#17150f]/70 shadow-[0_32px_90px_rgba(0,0,0,.32)] backdrop-blur-xl"><div className="flex items-center justify-between border-b border-white/8 px-5 py-4 sm:px-6"><div className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-lg bg-[linear-gradient(135deg,#e1c77f,#c67e5b)]"><Icon name="sparkle" className="size-3.5" /></span><div><p className="text-xs font-bold">Partner workspace</p><p className="mt-0.5 text-[10px] text-white/40">A clear picture of relevant discovery</p></div></div><span className="rounded-md border border-[#e6cc88]/20 bg-[#d6b36a]/10 px-2 py-1 text-[9px] font-bold tracking-[.11em] text-[#e9cf93]">ACTIVE</span></div><div className="grid gap-px bg-white/8 sm:grid-cols-[1.14fr_.86fr]"><div className="bg-[#17150f] p-5 sm:p-6"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-white/38">Product mapping</p><div className="mt-5 border border-white/10 bg-white/[.045] p-4"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-lg bg-[#f0e4c8] text-[#71562d]">◌</span><div className="min-w-0 flex-1"><p className="text-sm font-semibold">Ergonomic desk support</p><p className="mt-1 text-[10px] text-white/42">Workspace comfort · screen fatigue</p></div><span className="size-2 rounded-full bg-[#e8ca77] shadow-[0_0_14px_#e8ca77]" /></div></div><div className="mt-4 flex flex-wrap gap-2"><Tag>Back comfort</Tag><Tag>Desk work</Tag><Tag>Focused work</Tag></div></div><div className="bg-[#1d1811] p-5 sm:p-6"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#dfc486]">This month</p><p className="mt-5 text-4xl font-semibold tracking-[-.07em] text-[#fbf5e8]">84</p><p className="mt-1 text-xs text-white/43">relevant views</p><div className="mt-7 h-14 border-l border-b border-white/10 pl-2 pt-2"><svg className="h-full w-full" viewBox="0 0 130 50" preserveAspectRatio="none" aria-label="Upward trend"><path className="chart-line" d="M0 42 C18 38 26 40 41 29 S59 30 73 19 S96 25 108 11 S120 16 130 4" fill="none" stroke="#dcb96e" strokeWidth="3" /></svg></div></div></div></div></div>; }
function Tag({ children }: { children: React.ReactNode }) { return <span className="rounded-md border border-white/8 bg-white/5 px-2 py-1 text-[9px] text-white/48">{children}</span>; }
function Stat({ value, label }: { value: string; label: string }) { return <div className="pr-4 first:border-r first:border-white/10 first:mr-4"><p className="text-sm font-bold text-[#e7c983]">{value}</p><p className="mt-1 text-[10px] leading-4 text-white/40">{label}</p></div>; }
