import type { Metadata } from "next";
import Background from "@/components/background";
import { Icon } from "@/components/icon";
import SiteHeader from "@/components/site-header";
import TeamsAmbient from "@/components/teams-ambient";

export const metadata: Metadata = { title: "For teams" };

const framework = [
  ["01", "Start with the moment", "Map your support to a specific problem, rather than a broad audience label."],
  ["02", "Explain the fit", "Make the outcome, limits, and intended use of your offering clear."],
  ["03", "Show up usefully", "Be present when a person has a real need and context makes relevance obvious."],
];

export default function BusinessPage() {
  return <main className="teams-page page-enter business-sans relative min-h-screen overflow-hidden bg-[#122033] text-white"><Background mode="business" /><TeamsAmbient /><SiteHeader /><section className="relative z-10 mx-auto max-w-[1180px] px-5 pb-24 pt-14 sm:px-8 sm:pt-20">
    <div className="teams-hero relative grid gap-12 border-b border-white/20 pb-16 lg:grid-cols-[1fr_.8fr] lg:items-end"><div><p className="text-[11px] font-bold uppercase tracking-[.16em] text-[#96a9ff]">For thoughtful teams</p><h1 className="mt-6 max-w-3xl text-5xl font-semibold leading-[.94] tracking-[-.075em] text-white sm:text-6xl">Useful discovery is a better kind of visibility.</h1><p className="mt-7 max-w-xl text-[15px] leading-7 text-white/65">ProblemFirst gives people a clearer route through everyday problems—and gives relevant partners an earned place in that route.</p><a href="mailto:hello@problemfirst.app?subject=ProblemFirst%20team%20interest" className="pressable mt-9 inline-flex items-center gap-2 bg-[#f5f6f4] px-5 py-3 text-sm font-bold text-[#142033] hover:bg-[#aab8ff]">Talk to our team <Icon name="arrow" className="size-4" /></a></div><PartnerPreview /></div>
    <section className="teams-workflow relative mt-0 overflow-hidden border-b border-white/20 py-16"><TeamsAmbient variant="workflow" /><div className="relative z-10 grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-[11px] font-bold uppercase tracking-[.16em] text-[#e98864]">How it works</p><h2 className="mt-4 text-3xl font-bold leading-[1.02] tracking-[-.055em]">The product is not the whole story.</h2><p className="mt-5 max-w-xs text-sm leading-6 text-white/60">People are looking for a way forward. Any relevant support should make that next step more possible.</p></div><div className="grid gap-px border border-white/20 bg-white/20 sm:grid-cols-3">{framework.map(([number, title, copy]) => <article className="teams-workflow-step bg-[#122033]/90 p-6" key={number}><p className="text-[11px] font-bold tracking-[.14em] text-[#96a9ff]">{number}</p><h3 className="mt-12 text-lg font-bold tracking-[-.04em]">{title}</h3><p className="mt-3 text-sm leading-6 text-white/60">{copy}</p></article>)}</div></div></section>
    <section className="grid gap-10 py-16 lg:grid-cols-[1.1fr_.9fr]"><div className="border border-white/20 bg-[#182a42]"><div className="flex items-center justify-between border-b border-white/15 px-5 py-4"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#b6c2ef]">How relevance earns trust</p><span className="text-[10px] font-bold text-[#e98864]">EXAMPLE</span></div><div className="grid gap-px bg-white/15 sm:grid-cols-2"><div className="bg-[#16263b] p-6"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#b6c2ef]">A person is asking</p><p className="mt-5 text-xl font-semibold leading-7 tracking-[-.035em]">“How can I make my desk setup stop hurting my back?”</p></div><div className="bg-[#1d304b] p-6"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#b6c2ef]">A useful direction</p><div className="mt-5 border-l-2 border-[#e98864] pl-4"><p className="text-sm font-bold">Ergonomic workspace support</p><p className="mt-2 text-xs leading-5 text-white/60">Shown with a clear reason: it supports the exact adjustment the person is considering.</p></div></div></div></div><div className="self-center border-l-2 border-[#e98864] pl-6"><p className="text-[11px] font-bold uppercase tracking-[.16em] text-[#e98864]">For the long term</p><h2 className="mt-4 text-3xl font-bold leading-[1.02] tracking-[-.055em]">Context beats interruption.</h2><p className="mt-5 text-sm leading-7 text-white/60">Create a relationship with people at the moment your work makes sense—not through a louder message, but a better fit.</p></div></section>
  </section></main>;
}

function PartnerPreview() { return <div className="teams-dashboard relative border border-white/20 bg-[#182a42] p-5 shadow-[10px_10px_0_rgba(56,87,232,.45)]"><div className="flex items-center gap-2 border-b border-white/15 pb-4"><div><p className="text-xs font-bold">Partner workspace</p><p className="text-[10px] text-white/50">A concise view of relevant discovery</p></div></div><div className="mt-6 grid grid-cols-2 gap-px bg-white/15"><div className="bg-[#16263b] p-4"><p className="text-[10px] font-bold uppercase tracking-[.13em] text-[#b6c2ef]">Mapped support</p><p className="mt-6 text-sm font-bold">Ergonomic desk support</p><p className="mt-2 text-xs leading-5 text-white/55">Workspace comfort · focused work</p></div><div className="bg-[#1d304b] p-4"><p className="text-[10px] font-bold uppercase tracking-[.13em] text-[#b6c2ef]">This month</p><p className="mt-6 text-4xl font-bold tracking-[-.07em]">84</p><p className="mt-2 text-xs text-white/55">relevant views</p></div></div></div>; }
